# Generated by Django 5.2.17 on 2026-09-14 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('circuit', models.CharField(max_length=100)),
                ('source', models.CharField(default='Simulated demo data', max_length=250)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_race')],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=3)),
                ('number', models.PositiveIntegerField()),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(max_length=12)),
                ('pit', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='racing.race')),
            ],
            options={
                'ordering': ['driver', 'number'],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver', 'number'), name='unique_driver_lap'), models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='positive_lap'), models.CheckConstraint(condition=models.Q(('seconds__gt', 0), ('seconds__isnull', True), _connector='OR'), name='positive_time')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_a', models.CharField(max_length=3)),
                ('driver_b', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.race')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'race', 'driver_a', 'driver_b'), name='unique_bookmark')],
            },
        ),
    ]
